### ISSUE TITLE
Sugestões e Conveções

### ISSUE THREAD

**Issue by aislanmi** [OtavioVB/api_enem_microdados#21]
Olá, estive vendo seu projeto e tenho algumas sugestões de melhoria baseado nas convenções da linguagem C#.

1. Vi que você costuma usar acentuação na suas nomeações. Recomendo não usar, pode gerar alguns problemas em relação a caminho de arquivos, além de dificultar o desenvolvimento. 

2. O C# utiliza o padrão _CamelCase_ para classes, métodos e propriedades. Por exemplo, ao invés de **BUSCAR_INFORMACOES_DO_PARTICIPANTE** utilize **BuscarInformacoesDoParticipante**.

**Comment by OtavioVB** [comment]
> Olá, estive vendo seu projeto e tenho algumas sugestões de melhoria baseado nas convenções da linguagem C#.
> 
> 1. Vi que você costuma usar acentuação na suas nomeações. Recomendo não usar, pode gerar alguns problemas em relação a caminho de arquivos, além de dificultar o desenvolvimento.
> 2. O C# utiliza o padrão _CamelCase_ para classes, métodos e propriedades. Por exemplo, ao invés de **BUSCAR_INFORMACOES_DO_PARTICIPANTE** utilize **BuscarInformacoesDoParticipante**.

Legal @aislanmi, dois pontos muito importantes que você abordou que faz total sentido e eu não estava me importando muito... Apesar de eu estar utilizando o padrão ``UPPER_SNAKE_CASE`` acho que faz sentido utilizando o `padrão do C#`... Pesquisando um pouco mais sobre convenções de nomenclatura achei essa postagem do [StackOverflow](https://pt.stackoverflow.com/questions/31646/padr%C3%A3o-de-nomenclatura-no-c%C3%B3digo-para-o-c) que acredito ser muito produtivo.

Quanto aos acentos acredito que não há problemas em utilizar acentos, no entanto como apresentado no post do Maniero no StackOverflow: ``Decida se vai usar acentuação em identificadores ou não e mantenha o padrão, se aceitar acentos, todo mundo tem que respeitar a acentuação correta, não pode ficar escolhendo momentos para não acentuar.`` e em certos momentos eu deixei de utilizar, então as suas sugestões fazem total sentido!

**Comment by OtavioVB** [comment]
Gostaria de participar do projeto realizando um ``pull request`` com tais mudanças?

**Comment by aislanmi** [comment]
> Gostaria de participar do projeto realizando um `pull request` com tais mudanças?

Nice garoto, com certeza tenho interesse em participar. Vou contribuindo com o projeto conforme eu conseguir. :)

**Comment by OtavioVB** [comment]
> > Gostaria de participar do projeto realizando um `pull request` com tais mudanças?
> 
> Nice garoto, com certeza tenho interesse em participar. Vou contribuindo com o projeto conforme eu conseguir. :)

Show!!

**Comment by aislanmi** [comment]
> > > Gostaria de participar do projeto realizando um `pull request` com tais mudanças?
> > 
> > 
> > Nice garoto, com certeza tenho interesse em participar. Vou contribuindo com o projeto conforme eu conseguir. :)
> 
> Show!!

Falai bro, fiz algumas melhorias considerando algumas boas práticas da linguagem. Qualquer dúvida me encontro a disposição.

- [_pull request_](https://github.com/OtavioVB/api_enem_microdados/pull/22)
